import { Vector3, AngleResult } from '../types';

/**
 * Calculates the Pitch and Yaw between two points.
 * Standard implementation for WC3/FPS style cameras (Z-up coordinate system commonly used in WC3).
 */
export const calculateAngles = (src: Vector3, dst: Vector3): AngleResult => {
    const deltaX = dst.x - src.x;
    const deltaY = dst.y - src.y;
    const deltaZ = dst.z - src.z;

    // Horizontal distance (Hypotenuse on the ground plane)
    const dist2D = Math.sqrt(deltaX * deltaX + deltaY * deltaY);
    
    // Total distance
    const dist3D = Math.sqrt(dist2D * dist2D + deltaZ * deltaZ);

    // Yaw (Left/Right) - Standard atan2(y, x)
    // Converted to degrees
    let yaw = Math.atan2(deltaY, deltaX) * (180.0 / Math.PI);

    // Pitch (Up/Down) - atan(z / horizontal_distance)
    // Note: In some engines pitch is inverted (negative looks up), but standard math:
    // Positive Z is up. Positive Pitch looks up.
    let pitch = Math.atan2(deltaZ, dist2D) * (180.0 / Math.PI);

    // Normalize Yaw to 0-360 for display clarity (optional logic)
    if (yaw < 0) {
        yaw += 360;
    }

    return {
        pitch,
        yaw,
        distance: dist3D
    };
};

export const generateCSharpCode = (config: { style: string, normalize: boolean, useDouble: boolean }) => {
    const floatType = config.useDouble ? 'double' : 'float';
    const mathClass = config.useDouble ? 'Math' : 'Mathf';
    const cast = config.useDouble ? '' : '(float)';
    
    let vectorType = 'Vector3';
    let xAcc = 'X'; 
    let yAcc = 'Y'; 
    let zAcc = 'Z';
    let imports = 'using System;';

    if (config.style === 'System.Numerics') {
        vectorType = 'Vector3'; // System.Numerics.Vector3
        imports += '\nusing System.Numerics;';
    } else if (config.style === 'Unity/Custom') {
        imports += '\nusing UnityEngine; // Or your custom vector lib';
    } else if (config.style === 'Unsafe/Memory') {
        vectorType = 'float*';
        xAcc = '[0]';
        yAcc = '[1]';
        zAcc = '[2]';
        imports += '\nusing System.Runtime.InteropServices;';
    }

    const normalizationCode = config.normalize ? `
        // Normalize Yaw to -180 to 180 or 0 to 360 depending on game requirements
        while (yaw <= -180.0f) yaw += 360.0f;
        while (yaw > 180.0f) yaw -= 360.0f;` : '';

    const timestamp = new Date().toLocaleString();

    return `/*
 * Generated by DotA 1 DevTools
 * Timestamp: ${timestamp}
 * 
 * INSTRUCTIONS:
 * 1. Add this file to your C# Class Library project.
 * 2. Build the project to get the .DLL file.
 * 3. Inject the .DLL into Warcraft III.
 */

${imports}

public class Warcraft3CamHelper
{
    /// <summary>
    /// Calculates the view angles required for the source to look at the destination.
    /// Useful for DotA 1 / WC3 Camera tools.
    /// </summary>
    public static ${vectorType} CalcAngle(${vectorType} src, ${vectorType} dst)
    {
        // Calculate delta vector
        ${floatType} dx = dst.${xAcc} - src.${xAcc};
        ${floatType} dy = dst.${yAcc} - src.${yAcc};
        ${floatType} dz = dst.${zAcc} - src.${zAcc};

        // Calculate horizontal distance (hypotenuse)
        ${floatType} hyp = ${cast}Math.Sqrt(dx * dx + dy * dy);

        // Calculate Angles (in Degrees)
        ${floatType} yaw = ${cast}(Math.Atan2(dy, dx) * (180.0 / Math.PI));
        ${floatType} pitch = ${cast}(Math.Atan2(dz, hyp) * (180.0 / Math.PI)); // WC3 is Z-Up

        ${normalizationCode}

        // Return format depends on how the game stores angles. 
        // Usually X=Pitch, Y=Yaw, Z=Roll(0)
        ${config.style === 'Unsafe/Memory' 
            ? '// For unsafe pointers, you would typically write directly to memory here.' 
            : `return new ${vectorType.replace('*', '')}(pitch, yaw, 0);`
        } 
    }
}`.trim();
};